services:
  - type: web
    name: team-tasks-api
    env: node
    plan: free
    buildCommand: 'npm ci && npm rebuild better-sqlite3'
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        generateValue: true
      - key: DB_FILE
        value: /tmp/data.sqlite
      - key: SEED
        value: 'true'
    